# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#repository: "nicolas-van/bootstrap-4-github-pages"
# Build settings
# A list of the pages to display in the navigation bar
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.