# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
todobar: 32
autoseconds:
title: SpiderGamin
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  My personal website
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  SpiderGamin
author: SpiderGamin
#repository: "nicolas-van/bootstrap-4-github-pages"
# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
# A list of the pages to display in the navigation bar
header_pages: media
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh