name: Notification on push

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Spiders Website
        DISCORD_AVATAR: https://spidergamin.github.io/SpiderGaminIcon.png
      uses: Ilshidur/action-discord@master
      with:
        args: 'An update to my website has been released @Website Update'
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
